version: '3'
services:
  app:
    container_name: report-svc-app
    image: report-svc-app
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8082:8082"
    networks:
      - network
    depends_on:
      - postgresDb
    restart:  on-failure

  postgresDb:
    image: postgres:13.2
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - network
    volumes:
      - volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres


networks:
  network:

volumes:
  volume:
